### ISSUE TITLE
Joystick name changed

### ISSUE THREAD

**Issue by ppizzo** [tdammers/flightgear-joystick-config-tca#1]
Hi,

I noticed that, at least on my setup, the flightstick is now named `Thrustmaster-TA320-Copilot.xml` and not `Thrustmaster-TA320-Pilot.xml`. I don't know if it depends on the FlightGear version, because I started using FG only with the latest release.

My configuration:

- OS: Debian GNU/Linux Bookworm
- FlightGear: 2020.3.17

By the way, many thanks for your work, very much appreciated! 🙂

**Comment by tdammers** [comment]
Tbh, I have no idea why it would do that. Have you maybe changed the stick to a right-handed setup? I don't know if that's how it actually works, but I'd wager that maybe the stick detects this, and renames itself accordingly.

**Comment by tdammers** [comment]
If that's what's going on, then the obvious workaround is to copy the main configuration file and change the name in the XML; it should then load the same overlays. If you need a more elaborate setup, then that would require bigger changes to the way the configuration works, and I'm not sure I want to embark on that just yet. In any case, if you could confirm that my theory is correct, that would be great.

**Comment by ppizzo** [comment]
Hi, actually I changed the stick to a right-handed setup, but now I returned to the default left-handed setup and the stick is still identified as "Copilot" by FlightGear. I also tried to reset the Joystick configuration to the builtin default, removed the custom XML files and try to map a button: FG recreated the file with "Copilot".

Anyway, maybe it depends on something stuck on my configuration when I swapped the layout, it's not a problem: I renamed the file and adapted the lines in the initial nasal script for the overlay, and it works perfectly.

Thanks again, I close the issue.

I share with you my additional mappings for the quadrant:

```xml
  <axis n="2">
    <desc type="string">Flaps</desc>
    <binding>
      <command type="string">property-scale</command>
      <property type="string">/controls/flight/flaps</property>
      <factor type="double">0.5</factor>
      <offset type="double">1</offset>
      <power type="double">1</power>
    </binding>
  </axis>
  <axis n="5">
    <desc type="string">Speedbrake</desc>
    <binding>
      <command type="string">property-scale</command>
      <property type="string">/controls/flight/speedbrake</property>
      <factor type="double">0.5</factor>
      <offset type="double">1</offset>
      <power type="double">1</power>
    </binding>
  </axis>

  <button n="19">
    <desc type="string">Parking brakes</desc>
    <binding>
      <command type="string">nasal</command>
      <script type="string">
        setprop("/controls/gear/brake-parking", 1);
      </script>
    </binding>
    <mod-up>
      <binding>
        <command type="string">nasal</command>
        <script type="string">
          setprop("/controls/gear/brake-parking", 0);
        </script>
       </binding>
    </mod-up>
  </button>
  <button n="20">
    <desc type="string">Gear</desc>
    <binding>
      <command type="string">nasal</command>
      <script type="string">
        setprop("/controls/gear/gear-down", 0)
      </script>
    </binding>
    <mod-up>
      <binding>
        <command type="string">nasal</command>
        <script type="string">
          setprop("/controls/gear/gear-down", 1)
        </script>
       </binding>
    </mod-up>
  </button>
```
